# Generated by Django 4.1.11 on 2023-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='DOB',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
