# Generated by Django 4.1.11 on 2024-01-10 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_platform', '0005_staff_admin_student_subadmin_subadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_admin',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student_subadmin',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
